[tool.poetry]
name = "image-modalities-classifier"
version = "0.1.0"
description = ""
authors = ["Juan Trelles <jtrell2@uic.edu>"]
readme = "README.md"
packages = [{ include = "image_modalities_classifier" }]

[tool.poetry.dependencies]
# needed always: training + inference
python = ">=3.10,<3.15"
pandas = "^2.0"
scikit-learn = "^1.7"
scikit-image = "^0.25.2"
pytorch-lightning = "^1.9.0"
requests = "^2.31.0"         # security issue dependabot

# only needed for training
iterative-stratification = "^0.1.7"
matplotlib = "^3.9"
pyarrow = "^22.0.0"
tqdm = "^4.64.1"
torch = "^2.9.1"
torchvision = "^0.24.1"

# made extra for compatibility with rapids on biosearch-core
# wandb and rapids have incompatible protobuff requirements
wandb = { version = "^0.13.11", optional = true }

[tool.poetry.group.dev.dependencies]
pytest = "^8.0"
black = "^25.0"
pylint = "^4.0"
ipykernel = "^7.0"
ipywidgets = "^8.0"
multidict = "^6.1.0"

[tool.poetry.extras]
#torch = ["torch", "torchvision"]
wandb = ["wandb"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
train_image_modality_model = 'image_modalities_classifier.train:main'
train_model = 'image_modalities_classifier.train:main'
