[tool.poetry]
name = "biosearch-core"
version = "0.1.0"
description = ""
authors = ["Juan Trelles <juantrelles@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.15"
pandas = "^2.0"
pyarrow = "^22.0"
Pillow = "^10.1"
psycopg = { extras = ["binary"], version = "^3.1.8" }
python-dotenv = "^0.21.1"
tqdm = "^4.64"
flask = "^2.3.2"
flask-cors = "^3.0.10"
rich = "^13.3.2"

[tool.poetry.group.ml]
optional = true

[tool.poetry.group.ml.dependencies]
umap-learn = "^0.5.3"
cudf-cu12 = { version = "^25.12", source = "rapids", markers = "sys_platform == 'linux'" }
dask-cudf-cu12 = { version = "^25.12", source = "rapids", markers = "sys_platform == 'linux'" }
cuml-cu12 = { version = "^25.12", source = "rapids", markers = "sys_platform == 'linux'" }
torch = "^2.9.1"
torchvision = "^0.24.1"
image_modalities_classifier = { git = "https://github.com/uic-evl/bio-search.git", subdirectory = "image-modalities-classifier", branch = "fix/lucene10" }

[[tool.poetry.source]]
name = "rapids"
url = "https://pypi.nvidia.com"
priority = "explicit"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0"
ipykernel = "^7.0"
black = "^25.0"
pylint = "^4.0"
pytest-postgresql = "^7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
biosearch_core_export = 'biosearch_core.indexing.export:main'
